# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

# file-version: 1.0

version: 2

multi-ecosystem-groups:
  maintenance:
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Europe/Berlin"

    cooldown:
      default-days: 7

    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

updates:
  - package-ecosystem: "npm"

    directory: "/"

    versioning-strategy: "increase"

    target-branch: "master"

    commit-message:
      include: "scope"
      prefix: "npm"

    rebase-strategy: "disabled"

    multi-ecosystem-group: "maintenance"

    patterns: [ "*" ]

  - package-ecosystem: "github-actions"

    directory: "/"

    target-branch: "master"

    commit-message:
      prefix: "github-actions"

    ignore:
      - dependency-name: "mimmi20/ci"
      - dependency-name: "release-drafter/release-drafter"

    rebase-strategy: "disabled"

    multi-ecosystem-group: "maintenance"

    patterns: [ "*" ]
